# =============
# builder stage
# =============
FROM node:17.2.0

WORKDIR node-http

COPY src/ .
COPY .package*.json ./
COPY .env.production .

RUN npm ci --production

USER node

ENV NODE_VERSION=17.2.0
ENV NODE_ENV=production

EXPOSE 3000:3000
# ================
# production stage
# ================
FROM alpine:latest AS production

COPY --from=builder /node-http .

CMD ["npm", "run", "start:prod"]
