hello_world:
	clang++ -Wall -std=c++17 hello_world.cpp -o hello_world && ./hello_world

rhw:
	rm hello_world

io:
	clang++ -Wall -std=c++17 io.cpp -o io && ./io

rio:
	rm io

cf:
	clang++ -Wall -std=c++17 control_flow.cpp -o control_flow && ./control_flow

rcf:
	rm control_flow

funcs:
	clang++ -Wall -std=c++17 functions.cpp -o functions && ./functions

rfuncs:
	rm functions

arr:
	clang++ -Wall -std=c++17 arrays.cpp -o arrays && ./arrays

rarr:
	rm arrays

ptrs:
	clang++ -Wall -std=c++17 pointers.cpp -o pointers && ./pointers

rptrs:
	rm pointers
