version: '3.8'

volumes:
  db:
    driver: local

services:
  api:
    container_name: go-http
    image: go-http-app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/data/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
