# =============
# builder stage
# =============
FROM golang:latest AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download && go mod verify
COPY . .
RUN go build -v -o main .
EXPOSE 3000:3000

# ================
# production stage
# ================
FROM alpine:latest AS production
COPY --from=builder /app .
CMD ["./main"]
