version: '3.8'

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - db:/data/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
volumes:
  db:
    driver: local
